# GitHub Action to Build a Docker Image and Deploy to Azure Web App
name: Staging - Deploy - Backend - Bintanproperties

on:
  workflow_dispatch:

env:
  IMAGE_NAME: llyidregistry.azurecr.io/devops

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker image
        run: docker pull herdanis/simple-service:1.0

  push:
    # needs: build
    runs-on: ubuntu-latest
    environment: prod

    steps:
      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to Azure Container Registry
      - name: Login to ACR
        run: az acr login --name llyidregistry

      # Push the Docker image to Azure Container Registry
      # - name: Push Docker image to ACR
      #   run: docker push $IMAGE_NAME

      - name: Test push image
        run: |
          docker tag herdanis/simple-service:1.0 llyidregistry.azurecr.io/devops:${{ github.sha }}-${{ secrets.INI_SECRET }}
          docker push llyidregistry.azurecr.io/devops:${{ github.sha }}-${{ secrets.INI_SECRET }}

      # Logout from Azure
      - name: Azure logout
        run: az logout

        # deploy:
        #   runs-on: ubuntu-latest
        #   needs: build
        #   environment:
        #     name: "production"
        #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        #   steps:
        #     # Deploy Docker Image to Azure Web App
        #     - name: Deploy to Azure Web App
        #       id: deploy-to-webapp
        #       uses: azure/webapps-deploy@v2
        #       with:
        #         app-name: "bintanproperties-backend-staging"
        #         slot-name: "production"
        #         publish-profile: ${{ secrets.AzureAppService_PublishProfile_c1f8f32787ba4458a076755b2781460c }}
        #         images: $IMAGE_NAME
        #         secure-environment-variables:
        #           CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}
        #           CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}
        #           AZURE_BLOBS_STORAGE=${{ secrets.AZURE_BLOBS_STORAGE }}
        #           SMTP_PASS=${{ secrets.SMTP_PASS }}
        #           SMTP_USER=${{ secrets.SMTP_USER }}
        #     - name: Azure Logout
        #       run: az logout
